{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import import_ipynb\n",
    "import tmblr\n",
    "import Seguire\n",
    "import requests\n",
    "\n",
    "\n",
    "post,caption, url = None, None, None\n",
    "tags = []\n",
    "\n",
    "\n",
    "while not Seguire.Training(tags):\n",
    "    post,caption,url = tmblr.returnResponse()\n",
    "    tags = tmblr.parseTags(post['tags'])\n",
    "#print (url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "importing Jupyter notebook from tmblr.ipynb\n",
      "importing Jupyter notebook from Seguire.ipynb\n",
      "1.7078946331485023e-06 x 3.5998723257716592e-06\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<queue.Queue at 0x7effacf02050>"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 420, in polling_action_cb\n",
      "    allowed_updates=allowed_updates,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 117, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 2726, in get_updates\n",
      "    'getUpdates', data, timeout=float(read_latency) + float(timeout), api_kwargs=api_kwargs\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 235, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 354, in post\n",
      "    **urlopen_kwargs,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 420, in polling_action_cb\n",
      "    allowed_updates=allowed_updates,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 117, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 2726, in get_updates\n",
      "    'getUpdates', data, timeout=float(read_latency) + float(timeout), api_kwargs=api_kwargs\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 235, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 354, in post\n",
      "    **urlopen_kwargs,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 420, in polling_action_cb\n",
      "    allowed_updates=allowed_updates,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 117, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 2726, in get_updates\n",
      "    'getUpdates', data, timeout=float(read_latency) + float(timeout), api_kwargs=api_kwargs\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 235, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 354, in post\n",
      "    **urlopen_kwargs,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    }
   ],
   "source": [
    "from telegram.ext import Updater\n",
    "from telegram.ext import CommandHandler\n",
    "import import_ipynb\n",
    "import tmblr\n",
    "import Seguire\n",
    "import requests\n",
    "\n",
    "\n",
    "updater = Updater(token='1159213896:AAGubBWb16oCfb5EYpIjxGZiY_9Xz-BMwsA', use_context=True)\n",
    "\n",
    "\n",
    "dispatcher = updater.dispatcher\n",
    "\n",
    "def start(update, context):\n",
    "    post,caption,url = None, None, None\n",
    "    tags = []\n",
    "\n",
    "\n",
    "    while not Seguire.Training(tags):\n",
    "        post,caption,url = tmblr.returnResponse()\n",
    "        tags = tmblr.parseTags(post['tags'])\n",
    "    context.bot.send_message(chat_id=update.effective_chat.id, text=url)\n",
    "\n",
    "start_handler = CommandHandler('start', start)\n",
    "dispatcher.add_handler(start_handler)\n",
    "\n",
    "updater.start_polling()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 420, in polling_action_cb\n",
      "    allowed_updates=allowed_updates,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 117, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 2726, in get_updates\n",
      "    'getUpdates', data, timeout=float(read_latency) + float(timeout), api_kwargs=api_kwargs\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 235, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 354, in post\n",
      "    **urlopen_kwargs,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 420, in polling_action_cb\n",
      "    allowed_updates=allowed_updates,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 117, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 2726, in get_updates\n",
      "    'getUpdates', data, timeout=float(read_latency) + float(timeout), api_kwargs=api_kwargs\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 235, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 354, in post\n",
      "    **urlopen_kwargs,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 420, in polling_action_cb\n",
      "    allowed_updates=allowed_updates,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 117, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 2726, in get_updates\n",
      "    'getUpdates', data, timeout=float(read_latency) + float(timeout), api_kwargs=api_kwargs\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 235, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 354, in post\n",
      "    **urlopen_kwargs,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 420, in polling_action_cb\n",
      "    allowed_updates=allowed_updates,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 117, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 2726, in get_updates\n",
      "    'getUpdates', data, timeout=float(read_latency) + float(timeout), api_kwargs=api_kwargs\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 235, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 354, in post\n",
      "    **urlopen_kwargs,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 420, in polling_action_cb\n",
      "    allowed_updates=allowed_updates,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 117, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 2726, in get_updates\n",
      "    'getUpdates', data, timeout=float(read_latency) + float(timeout), api_kwargs=api_kwargs\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 235, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 354, in post\n",
      "    **urlopen_kwargs,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 420, in polling_action_cb\n",
      "    allowed_updates=allowed_updates,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 117, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 2726, in get_updates\n",
      "    'getUpdates', data, timeout=float(read_latency) + float(timeout), api_kwargs=api_kwargs\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 235, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 354, in post\n",
      "    **urlopen_kwargs,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 420, in polling_action_cb\n",
      "    allowed_updates=allowed_updates,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 117, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 2726, in get_updates\n",
      "    'getUpdates', data, timeout=float(read_latency) + float(timeout), api_kwargs=api_kwargs\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 235, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 354, in post\n",
      "    **urlopen_kwargs,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 420, in polling_action_cb\n",
      "    allowed_updates=allowed_updates,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 117, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 2726, in get_updates\n",
      "    'getUpdates', data, timeout=float(read_latency) + float(timeout), api_kwargs=api_kwargs\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 235, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 354, in post\n",
      "    **urlopen_kwargs,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 420, in polling_action_cb\n",
      "    allowed_updates=allowed_updates,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 117, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 2726, in get_updates\n",
      "    'getUpdates', data, timeout=float(read_latency) + float(timeout), api_kwargs=api_kwargs\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 235, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 354, in post\n",
      "    **urlopen_kwargs,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 420, in polling_action_cb\n",
      "    allowed_updates=allowed_updates,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 117, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 2726, in get_updates\n",
      "    'getUpdates', data, timeout=float(read_latency) + float(timeout), api_kwargs=api_kwargs\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 235, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 354, in post\n",
      "    **urlopen_kwargs,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 420, in polling_action_cb\n",
      "    allowed_updates=allowed_updates,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 117, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 2726, in get_updates\n",
      "    'getUpdates', data, timeout=float(read_latency) + float(timeout), api_kwargs=api_kwargs\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 235, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 354, in post\n",
      "    **urlopen_kwargs,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 420, in polling_action_cb\n",
      "    allowed_updates=allowed_updates,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 117, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 2726, in get_updates\n",
      "    'getUpdates', data, timeout=float(read_latency) + float(timeout), api_kwargs=api_kwargs\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 235, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 354, in post\n",
      "    **urlopen_kwargs,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 420, in polling_action_cb\n",
      "    allowed_updates=allowed_updates,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 117, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 2726, in get_updates\n",
      "    'getUpdates', data, timeout=float(read_latency) + float(timeout), api_kwargs=api_kwargs\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 235, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 354, in post\n",
      "    **urlopen_kwargs,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py\", line 420, in polling_action_cb\n",
      "    allowed_updates=allowed_updates,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 117, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 2726, in get_updates\n",
      "    'getUpdates', data, timeout=float(read_latency) + float(timeout), api_kwargs=api_kwargs\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/bot.py\", line 235, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 354, in post\n",
      "    **urlopen_kwargs,\n",
      "  File \"/home/gabriel/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    }
   ],
   "source": [
    "from telegram.ext import Updater\n",
    "from telegram.ext import CommandHandler\n",
    "\n",
    "updater = Updater(token='1159213896:AAGubBWb16oCfb5EYpIjxGZiY_9Xz-BMwsA', use_context=True)\n",
    "updater.stop()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
